# ft_clk => 100000000Hz
create_clock -period 10.0 -name ft_clk_0 -waveform {0.000 5.000} [get_ports ft_clk]
set_property PACKAGE_PIN F5 [get_ports {ft_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_clk}]
set_property PACKAGE_PIN F3 [get_ports {ft_rxf}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_rxf}]
set_property PACKAGE_PIN F4 [get_ports {ft_txe}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_txe}]
set_property PACKAGE_PIN B7 [get_ports {ft_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[0]}]
set_property PACKAGE_PIN A7 [get_ports {ft_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[1]}]
set_property PACKAGE_PIN B6 [get_ports {ft_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[2]}]
set_property PACKAGE_PIN B5 [get_ports {ft_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[3]}]
set_property PACKAGE_PIN C3 [get_ports {ft_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[4]}]
set_property PACKAGE_PIN C2 [get_ports {ft_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[5]}]
set_property PACKAGE_PIN R6 [get_ports {ft_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[6]}]
set_property PACKAGE_PIN R7 [get_ports {ft_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[7]}]
set_property PACKAGE_PIN C7 [get_ports {ft_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[8]}]
set_property PACKAGE_PIN C6 [get_ports {ft_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[9]}]
set_property PACKAGE_PIN R12 [get_ports {ft_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[10]}]
set_property PACKAGE_PIN T12 [get_ports {ft_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[11]}]
set_property PACKAGE_PIN T9 [get_ports {ft_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[12]}]
set_property PACKAGE_PIN T10 [get_ports {ft_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[13]}]
set_property PACKAGE_PIN B4 [get_ports {ft_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[14]}]
set_property PACKAGE_PIN A3 [get_ports {ft_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[15]}]
set_property PACKAGE_PIN G2 [get_ports {ft_be[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_be[0]}]
set_property PACKAGE_PIN G1 [get_ports {ft_be[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_be[1]}]
set_property PACKAGE_PIN D3 [get_ports {ft_rd}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_rd}]
set_property PACKAGE_PIN E3 [get_ports {ft_wr}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_wr}]
set_property PACKAGE_PIN E5 [get_ports {ft_oe}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_oe}]
# set_clock_groups -group [get_clocks -include_generated_clocks clk_0] \
#   -group [get_clocks -include_generated_clocks ft_clk_0] -asynchronous
set_clock_groups -async -group [get_clocks -include_generated_clocks ft_clk_0]

set_input_delay -clock [get_clocks ft_clk_0] -min -add_delay 0.000 [get_ports ft_rxf]
set_input_delay -clock [get_clocks ft_clk_0] -max -add_delay 0.001 [get_ports ft_rxf]
set_input_delay -clock [get_clocks ft_clk_0] -min -add_delay 0.000 [get_ports ft_txe]
set_input_delay -clock [get_clocks ft_clk_0] -max -add_delay 0.001 [get_ports ft_txe]
set_output_delay -clock [get_clocks ft_clk_0] -min -add_delay 0.000 [get_ports {ft_data[*]}]
set_output_delay -clock [get_clocks ft_clk_0] -max -add_delay 0.001 [get_ports {ft_data[*]}]
set_false_path -to [get_ports {ft_data[*]}]
set_output_delay -clock [get_clocks ft_clk_0] -min -add_delay 0.000 [get_ports {ft_be[*]}]
set_output_delay -clock [get_clocks ft_clk_0] -max -add_delay 0.001 [get_ports {ft_be[*]}]
set_false_path -to [get_ports {ft_be[*]}]
set_output_delay -clock [get_clocks ft_clk_0] -min -add_delay 0.000 [get_ports {ft_oe}]
set_output_delay -clock [get_clocks ft_clk_0] -max -add_delay 0.001 [get_ports {ft_oe}]
set_false_path -to [get_ports {ft_oe}]
set_output_delay -clock [get_clocks ft_clk_0] -min -add_delay 0.000 [get_ports {ft_rd}]
set_output_delay -clock [get_clocks ft_clk_0] -max -add_delay 0.001 [get_ports {ft_rd}]
set_false_path -to [get_ports {ft_rd}]
set_output_delay -clock [get_clocks ft_clk_0] -min -add_delay 0.000 [get_ports {ft_wr}]
set_output_delay -clock [get_clocks ft_clk_0] -max -add_delay 0.001 [get_ports {ft_wr}]
set_false_path -to [get_ports {ft_wr}]