
# set_property PACKAGE_PIN D17 [get_ports "clk_p"] 
# set_property IOSTANDARD LVDS [get_ports "clk_p"] 
# #
# set_property PACKAGE_PIN C17 [get_ports "clk_n"] 
# set_property IOSTANDARD LVDS [get_ports "clk_n"]

# ft_clk => 100000000Hz
# create_clock -period 10.0 -name ft_clk_0 -waveform {0.000 5.000} [get_ports ft_clk]
set_property PACKAGE_PIN V4 [get_ports {ft_clk}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_clk}]
set_property PACKAGE_PIN W6 [get_ports {ft_rxf}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_rxf}]
set_property PACKAGE_PIN W5 [get_ports {ft_txe}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_txe}]

set_property PACKAGE_PIN R3 [get_ports {ft_data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[0]}]
set_property PACKAGE_PIN R2 [get_ports {ft_data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[1]}]
set_property PACKAGE_PIN T1 [get_ports {ft_data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[2]}]
set_property PACKAGE_PIN U2 [get_ports {ft_data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[3]}]
set_property PACKAGE_PIN U1 [get_ports {ft_data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[4]}]
set_property PACKAGE_PIN V2 [get_ports {ft_data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[5]}]
set_property PACKAGE_PIN W2 [get_ports {ft_data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[6]}]
set_property PACKAGE_PIN W1 [get_ports {ft_data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[7]}]
set_property PACKAGE_PIN Y2 [get_ports {ft_data[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[8]}]
set_property PACKAGE_PIN Y1 [get_ports {ft_data[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[9]}]
set_property PACKAGE_PIN U3 [get_ports {ft_data[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[10]}]
set_property PACKAGE_PIN V3 [get_ports {ft_data[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[11]}]
set_property PACKAGE_PIN AB3 [get_ports {ft_data[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[12]}]
set_property PACKAGE_PIN AB2 [get_ports {ft_data[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[13]}]
set_property PACKAGE_PIN AB1 [get_ports {ft_data[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[14]}]
set_property PACKAGE_PIN AA1 [get_ports {ft_data[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[15]}]

set_property PACKAGE_PIN AB8 [get_ports {ft_data[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[16]}]
set_property PACKAGE_PIN AA8 [get_ports {ft_data[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[17]}]
set_property PACKAGE_PIN V9 [get_ports {ft_data[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[18]}]
set_property PACKAGE_PIN AB7 [get_ports {ft_data[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[19]}]
set_property PACKAGE_PIN AB6 [get_ports {ft_data[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[20]}]
set_property PACKAGE_PIN Y3 [get_ports {ft_data[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[21]}]
set_property PACKAGE_PIN AA4 [get_ports {ft_data[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[22]}]
set_property PACKAGE_PIN AA5 [get_ports {ft_data[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[23]}]
set_property PACKAGE_PIN AB5 [get_ports {ft_data[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[24]}]
set_property PACKAGE_PIN AA3 [get_ports {ft_data[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[25]}]
set_property PACKAGE_PIN Y4 [get_ports {ft_data[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[26]}]
set_property PACKAGE_PIN Y7 [get_ports {ft_data[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[27]}]
set_property PACKAGE_PIN Y8 [get_ports {ft_data[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[28]}]
set_property PACKAGE_PIN W7 [get_ports {ft_data[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[29]}]
set_property PACKAGE_PIN V7 [get_ports {ft_data[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[30]}]
set_property PACKAGE_PIN V8 [get_ports {ft_data[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_data[31]}]


set_property PACKAGE_PIN R6 [get_ports {ft_be[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_be[0]}]
set_property PACKAGE_PIN T6 [get_ports {ft_be[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_be[1]}]
set_property PACKAGE_PIN U6 [get_ports {ft_be[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_be[2]}]
set_property PACKAGE_PIN V5 [get_ports {ft_be[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_be[3]}]


set_property PACKAGE_PIN R4 [get_ports {ft_rd}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_rd}]
set_property PACKAGE_PIN U5 [get_ports {ft_wr}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_wr}]
set_property PACKAGE_PIN T5 [get_ports {ft_oe}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_oe}]
set_property PACKAGE_PIN T4 [get_ports {ft_siwu}]
set_property IOSTANDARD LVCMOS18 [get_ports {ft_siwu}]

# set_clock_groups -async -group [get_clocks -include_generated_clocks ft_clk_0]

set_property PACKAGE_PIN AA20 [get_ports {led}]
set_property IOSTANDARD LVCMOS33 [get_ports {led}]