/*
    This file was generated automatically by Alchitry Labs 2.0.30-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module alchitry_top (
        input wire ft_clk,
        input wire ft_rxf,
        input wire ft_txe,
        inout wire [31:0] ft_data,
        inout wire [3:0] ft_be,
        output reg led,
        output reg ft_rd,
        output reg ft_wr,
        output reg ft_oe,
        output reg ft_siwu,
        inout wire [15:0] ddr3_dq,
        inout wire [1:0] ddr3_dqs_n,
        inout wire [1:0] ddr3_dqs_p,
        output reg [14:0] ddr3_addr,
        output reg [2:0] ddr3_ba,
        output reg ddr3_ras_n,
        output reg ddr3_cas_n,
        output reg ddr3_we_n,
        output reg ddr3_reset_n,
        output reg ddr3_ck_p,
        output reg ddr3_ck_n,
        output reg ddr3_cke,
        output reg ddr3_cs_n,
        output reg [1:0] ddr3_dm,
        output reg ddr3_odt
    );

    // need to hold this line up, should have just been a pullup
    assign ft_siwu = 1;

    localparam _MP_STAGES_2042760660 = 3'h4;
    logic clk_out1;
    logic clk_out2;
    logic clock_locked;
    
    clk_wiz_0 clk_wiz(
        .reset(0), .clk_in1(ft_clk),
        .clk_out1(clk_out1), .clk_out2(clk_out2),
        .locked(clock_locked)
    );

    logic [14:0] M_mig_ddr3_addr;
    logic [2:0] M_mig_ddr3_ba;
    logic M_mig_ddr3_ras_n;
    logic M_mig_ddr3_cas_n;
    logic M_mig_ddr3_we_n;
    logic M_mig_ddr3_reset_n;
    logic M_mig_ddr3_ck_p;
    logic M_mig_ddr3_ck_n;
    logic M_mig_ddr3_cke;
    logic M_mig_ddr3_cs_n;
    logic [1:0] M_mig_ddr3_dm;
    logic M_mig_ddr3_odt;
    LucidGlobals::G_Memory_in M_mig_mem_in;
    LucidGlobals::G_Memory_out M_mig_mem_out;
    logic M_mig_ui_clk;
    logic M_mig_sync_rst;
    logic M_mig_init_calib_complete;

    mig_wrapper mig (
        .ddr3_dq(ddr3_dq),
        .ddr3_dqs_n(ddr3_dqs_n),
        .ddr3_dqs_p(ddr3_dqs_p),
        .sys_rst(!clock_locked),
        .sys_clk(clk_out1),
        .clk_ref(clk_out2),
        .ddr3_addr(M_mig_ddr3_addr),
        .ddr3_ba(M_mig_ddr3_ba),
        .ddr3_ras_n(M_mig_ddr3_ras_n),
        .ddr3_cas_n(M_mig_ddr3_cas_n),
        .ddr3_we_n(M_mig_ddr3_we_n),
        .ddr3_reset_n(M_mig_ddr3_reset_n),
        .ddr3_ck_p(M_mig_ddr3_ck_p),
        .ddr3_ck_n(M_mig_ddr3_ck_n),
        .ddr3_cke(M_mig_ddr3_cke),
        .ddr3_cs_n(M_mig_ddr3_cs_n),
        .ddr3_dm(M_mig_ddr3_dm),
        .ddr3_odt(M_mig_ddr3_odt),
        .mem_in(M_mig_mem_in),
        .mem_out(M_mig_mem_out),
        .ui_clk(M_mig_ui_clk),
        .sync_rst(M_mig_sync_rst),
        .init_calib_complete(M_mig_init_calib_complete)
    );

    logic clk;
    logic rst;

    assign clk = M_mig_ui_clk;
    assign rst = M_mig_sync_rst;
    assign led = M_mig_init_calib_complete;
    //assign led = M_mig_sync_rst;
    
    localparam _MP_BUS_WIDTH_803046331 = 6'h20;
    localparam _MP_TX_BUFFER_803046331 = 9'h100;
    localparam _MP_RX_BUFFER_803046331 = 9'h100;
    localparam _MP_PRIORITY_803046331 = {{8'h52, 8'h58}};
    localparam _MP_PREEMPT_803046331 = 1'h0;
    logic M_ft_ft_rxf;
    logic M_ft_ft_txe;
    logic M_ft_ft_rd;
    logic M_ft_ft_wr;
    logic M_ft_ft_oe;
    logic [31:0] M_ft_ui_din;
    logic [3:0] M_ft_ui_din_be;
    logic M_ft_ui_din_valid;
    logic M_ft_ui_din_full;
    logic [31:0] M_ft_ui_dout;
    logic [3:0] M_ft_ui_dout_be;
    logic M_ft_ui_dout_empty;
    logic M_ft_ui_dout_get;
    
    ft #(
        .BUS_WIDTH(_MP_BUS_WIDTH_803046331),
        .TX_BUFFER(_MP_TX_BUFFER_803046331),
        .RX_BUFFER(_MP_RX_BUFFER_803046331),
        .PRIORITY(_MP_PRIORITY_803046331),
        .PREEMPT(_MP_PREEMPT_803046331)
    ) ft (
        .ft_clk(clk_out1),
        .ft_data(ft_data),
        .ft_be(ft_be),
        .clk(clk),
        .rst(rst),
        .ft_rxf(M_ft_ft_rxf),
        .ft_txe(M_ft_ft_txe),
        .ft_rd(M_ft_ft_rd),
        .ft_wr(M_ft_ft_wr),
        .ft_oe(M_ft_ft_oe),
        .ui_din(M_ft_ui_din),
        .ui_din_be(M_ft_ui_din_be),
        .ui_din_valid(M_ft_ui_din_valid),
        .ui_din_full(M_ft_ui_din_full),
        .ui_dout(M_ft_ui_dout),
        .ui_dout_be(M_ft_ui_dout_be),
        .ui_dout_empty(M_ft_ui_dout_empty),
        .ui_dout_get(M_ft_ui_dout_get)
    );

    typedef enum {WRITE_DATA, WRITE_CMD, READ_CMD, WAIT_READ, FT_WRITE} mem_state_sm;

    mem_state_sm mem_state_d, mem_state_q = WRITE_DATA;
    logic [127:0] mem_val_d, mem_val_q = 128'h000102030405060708090a0b0c0d0e0f;
    logic [2:0] addr_d, addr_q = 0;
    logic [1:0] mem_shift_count_d, mem_shift_count_q = 0;

    always_comb begin
        M_ft_ui_dout_get = 1;
        M_ft_ui_din_valid = 0;
        M_ft_ui_din = 0;
        M_ft_ui_din_be = 0;
        mem_state_d = mem_state_q;
        mem_val_d = mem_val_q;
        addr_d = addr_q;
        mem_shift_count_d = mem_shift_count_q;
        M_mig_mem_in.addr = 0;
        M_mig_mem_in.cmd = 0;
        M_mig_mem_in.enable = 0;
        M_mig_mem_in.wr_data = 0;
        M_mig_mem_in.wr_enable = 0;
        M_mig_mem_in.wr_mask = 0;
        case (mem_state_q)
        WRITE_DATA: begin
            M_mig_mem_in.wr_enable = 1;
            M_mig_mem_in.wr_data = mem_val_q;
            // M_ft_ui_din_valid = 1;
            // M_ft_ui_din = 32'hffffffff;
            // M_ft_ui_din_be = 4'hf;
            if (M_mig_mem_out.wr_rdy) begin
                mem_state_d = WRITE_CMD;
            end
        end
        WRITE_CMD: begin
            M_mig_mem_in.enable = 1;
            M_mig_mem_in.cmd = 0; // write
            M_mig_mem_in.addr = {addr_q, 3'b000};
            // M_ft_ui_din_valid = 1;
            // M_ft_ui_din = mem_val_d[31:0];
            // M_ft_ui_din_be = 4'hf;
            if (M_mig_mem_out.rdy) begin
                addr_d = addr_q + 1;
                mem_val_d = mem_val_q + 128'h01010101010101010101010101010101;
                mem_state_d = WRITE_DATA;
                if (addr_q == 3'h7) begin
                    mem_state_d = READ_CMD;
                    addr_d = 0;
                end
            end
        end
        READ_CMD: begin
            M_mig_mem_in.enable = 1;
            M_mig_mem_in.cmd = 1;
            M_mig_mem_in.addr = {addr_q, 3'b000};
            // M_ft_ui_din_valid = 1;
            // M_ft_ui_din = 32'h55555555;
            // M_ft_ui_din_be = 4'hf;
            if (M_mig_mem_out.rdy) begin
                mem_state_d = WAIT_READ;
            end
        end
        WAIT_READ: begin
            // M_ft_ui_din_valid = 1;
            // M_ft_ui_din = 32'h77777777;
            // M_ft_ui_din_be = 4'hf;
            if (M_mig_mem_out.rd_valid) begin
                mem_val_d = M_mig_mem_out.rd_data;
                mem_shift_count_d = 0;
                addr_d = addr_q + 1;
                mem_state_d = FT_WRITE;
                if (addr_q == 3'h7) begin
                    addr_d = 0;
                end
            end
        end
        FT_WRITE: begin
            if (!M_ft_ui_din_full) begin
                M_ft_ui_din = mem_val_q[127:96];
                M_ft_ui_din_be = 4'hf;
                M_ft_ui_din_valid = 1;
                mem_val_d[127:32] = mem_val_q[95:0];
                mem_val_d[31:0] = 0;
                mem_shift_count_d = mem_shift_count_q + 1;
                if (mem_shift_count_q == 3) begin
                    mem_state_d = READ_CMD;
                end
            end
        end
        endcase
    end

    always_ff @(posedge clk) begin
        if (rst) begin
            mem_state_q <= WRITE_DATA;
            mem_val_q <= 128'h000102030405060708090a0b0c0d0e0f;
            addr_q <= 0;
            mem_shift_count_q <= 0;
        end else begin
            mem_state_q <= mem_state_d;
            mem_val_q <= mem_val_d;
            addr_q <= addr_d;
            mem_shift_count_q <= mem_shift_count_d;
        end
    end
    
    always @* begin
        ddr3_addr = M_mig_ddr3_addr;
        ddr3_ba = M_mig_ddr3_ba;
        ddr3_ras_n = M_mig_ddr3_ras_n;
        ddr3_cas_n = M_mig_ddr3_cas_n;
        ddr3_we_n = M_mig_ddr3_we_n;
        ddr3_reset_n = M_mig_ddr3_reset_n;
        ddr3_ck_p = M_mig_ddr3_ck_p;
        ddr3_ck_n = M_mig_ddr3_ck_n;
        ddr3_cke = M_mig_ddr3_cke;
        ddr3_cs_n = M_mig_ddr3_cs_n;
        ddr3_dm = M_mig_ddr3_dm;
        ddr3_odt = M_mig_ddr3_odt;
        //M_mig_mem_in = {{28'bxxxxxxxxxxxxxxxxxxxxxxxxxxxx, 3'bxxx, 1'h0, 128'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, 1'h0, 16'h0}};
    end

    
    always @* begin
        M_ft_ft_rxf = ft_rxf;
        M_ft_ft_txe = ft_txe;
        ft_rd = M_ft_ft_rd;
        ft_wr = M_ft_ft_wr;
        ft_oe = M_ft_ft_oe;
    end
    
    
endmodule