/*
    This file was generated automatically by Alchitry Labs 2.0.30-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

// module ft #(
//         parameter BUS_WIDTH = 5'h10,
//         parameter TX_BUFFER = 8'h100,
//         parameter RX_BUFFER = 8'h100,
//         parameter PRIORITY = {{8'h54, 8'h58}},
//         parameter PREEMPT = 1'h0
//     ) (
//         input wire clk,
//         input wire rst,
//         input wire ft_clk,
//         input wire ft_rxf,
//         input wire ft_txe,
//         inout wire [(BUS_WIDTH)-1:0] ft_data,
//         inout wire [(BUS_WIDTH / 4'h8)-1:0] ft_be,
//         output reg ft_rd,
//         output reg ft_wr,
//         output reg ft_oe,
//         input wire [(BUS_WIDTH)-1:0] ui_din,
//         input wire [(BUS_WIDTH / 4'h8)-1:0] ui_din_be,
//         input wire ui_din_valid,
//         output reg ui_din_full,
//         output reg [(BUS_WIDTH)-1:0] ui_dout,
//         output reg [(BUS_WIDTH / 4'h8)-1:0] ui_dout_be,
//         output reg ui_dout_empty,
//         input wire ui_dout_get
//     );
//     logic [(BUS_WIDTH)-1:0] IO_ft_data;
//     assign ft_data = IO_ft_data;
//     logic [(BUS_WIDTH / 4'h8)-1:0] IO_ft_be;
//     assign ft_be = IO_ft_be;
//     logic L_6b1a727e_reading_bus;
//     logic [1:0] L_6b1a727e_prefered_state;
//     logic L_6b1a727e_can_write;
//     logic L_6b1a727e_can_read;
//     localparam E_State_IDLE = 2'h0;
//     localparam E_State_BUS_SWITCH = 2'h1;
//     localparam E_State_READ = 2'h2;
//     localparam E_State_WRITE = 2'h3;
//     logic [1:0] D_state_d, D_state_q = 0;
//     localparam _MP_WIDTH_181907911 = BUS_WIDTH + BUS_WIDTH / 4'h8;
//     localparam _MP_ENTRIES_181907911 = TX_BUFFER;
//     localparam _MP_SYNC_STAGES_181907911 = 2'h3;
//     logic [(_MP_WIDTH_181907911)-1:0] M_write_fifo_din;
//     logic M_write_fifo_wput;
//     logic M_write_fifo_full;
//     logic [(_MP_WIDTH_181907911)-1:0] M_write_fifo_dout;
//     logic M_write_fifo_rget;
//     logic M_write_fifo_empty;
    
//     fifo_generator_0 write_fifo(
//         .rst(rst),
//         .wr_clk(clk),
//         .rd_clk(ft_clk),
//         .din(M_write_fifo_din),
//         .wr_en(M_write_fifo_wput),
//         .rd_en(M_write_fifo_rget),
//         .dout(M_write_fifo_dout),
//         .full(M_write_fifo_full),
//         .empty(M_write_fifo_empty)
//     );


//     // async_fifo #(
//     //     .WIDTH(_MP_WIDTH_181907911),
//     //     .ENTRIES(_MP_ENTRIES_181907911),
//     //     .SYNC_STAGES(_MP_SYNC_STAGES_181907911)
//     // ) write_fifo (
//     //     .rclk(ft_clk),
//     //     .rrst(rst),
//     //     .wclk(clk),
//     //     .wrst(rst),
//     //     .din(M_write_fifo_din),
//     //     .wput(M_write_fifo_wput),
//     //     .full(M_write_fifo_full),
//     //     .dout(M_write_fifo_dout),
//     //     .rget(M_write_fifo_rget),
//     //     .empty(M_write_fifo_empty)
//     // );
    
    
//     localparam _MP_WIDTH_1952487625 = BUS_WIDTH + BUS_WIDTH / 4'h8;
//     localparam _MP_ENTRIES_1952487625 = RX_BUFFER;
//     localparam _MP_SYNC_STAGES_1952487625 = 2'h3;
//     logic [(_MP_WIDTH_1952487625)-1:0] M_read_fifo_din;
//     logic M_read_fifo_wput;
//     logic M_read_fifo_full;
//     logic [(_MP_WIDTH_1952487625)-1:0] M_read_fifo_dout;
//     logic M_read_fifo_rget;
//     logic M_read_fifo_empty;
    
//     async_fifo #(
//         .WIDTH(_MP_WIDTH_1952487625),
//         .ENTRIES(_MP_ENTRIES_1952487625),
//         .SYNC_STAGES(_MP_SYNC_STAGES_1952487625)
//     ) read_fifo (
//         .rclk(clk),
//         .rrst(rst),
//         .wclk(ft_clk),
//         .wrst(rst),
//         .din(M_read_fifo_din),
//         .wput(M_read_fifo_wput),
//         .full(M_read_fifo_full),
//         .dout(M_read_fifo_dout),
//         .rget(M_read_fifo_rget),
//         .empty(M_read_fifo_empty)
//     );
    
    
//     always @* begin
//         D_state_d = D_state_q;
        
//         M_write_fifo_wput = ui_din_valid;
//         M_write_fifo_din = {ui_din_be, ui_din};
//         ui_din_full = M_write_fifo_full;
//         ui_dout = M_read_fifo_dout[BUS_WIDTH - 1'h1:1'h0];
//         ui_dout_be = M_read_fifo_dout[((_MP_WIDTH_1952487625) - 1)-:BUS_WIDTH / 4'h8];
//         ui_dout_empty = M_read_fifo_empty;
//         M_read_fifo_rget = ui_dout_get;
//         M_read_fifo_din = {ft_be, ft_data};
//         M_read_fifo_wput = 1'h0;
//         M_write_fifo_rget = 1'h0;
//         ft_oe = 1'h1;
//         ft_rd = 1'h1;
//         ft_wr = 1'h1;
//         L_6b1a727e_reading_bus = D_state_q == 2'h1 || D_state_q == 2'h2;
//         IO_ft_data = L_6b1a727e_reading_bus ? {$bits(ft_data){1'bz}} : M_write_fifo_dout[BUS_WIDTH - 1'h1:1'h0];
//         IO_ft_be = L_6b1a727e_reading_bus ? {$bits(ft_be){1'bz}} : M_write_fifo_dout[((_MP_WIDTH_1952487625) - 1)-:BUS_WIDTH / 4'h8];
//         L_6b1a727e_prefered_state = 2'h0;
//         L_6b1a727e_can_write = ft_txe == 1'h0 && M_write_fifo_empty == 1'h0;
//         L_6b1a727e_can_read = ft_rxf == 1'h0 && M_read_fifo_full == 1'h0;
//         if (L_6b1a727e_can_write && (PRIORITY == {{8'h54, 8'h58}} || !L_6b1a727e_can_read)) begin
//             L_6b1a727e_prefered_state = 2'h3;
//         end
//         if (L_6b1a727e_can_read && (PRIORITY == {{8'h52, 8'h58}} || !L_6b1a727e_can_write)) begin
//             L_6b1a727e_prefered_state = 2'h1;
//         end
        
//         case (D_state_q)
//             2'h0: begin
//                 D_state_d = L_6b1a727e_prefered_state;
//             end
//             2'h1: begin
//                 ft_oe = 1'h0;
//                 D_state_d = 2'h2;
//             end
//             2'h2: begin
//                 ft_oe = M_read_fifo_full;
//                 ft_rd = M_read_fifo_full;
//                 M_read_fifo_wput = !ft_rxf;
//                 if (ft_rxf || M_read_fifo_full || (PREEMPT && L_6b1a727e_prefered_state == 2'h3)) begin
//                     D_state_d = L_6b1a727e_prefered_state;
//                 end
//             end
//             2'h3: begin
//                 ft_wr = M_write_fifo_empty;
//                 M_write_fifo_rget = !ft_txe;
//                 if (ft_txe || M_write_fifo_empty || (PREEMPT && L_6b1a727e_prefered_state == 2'h1)) begin
//                     D_state_d = L_6b1a727e_prefered_state;
//                 end
//             end
//         endcase
//     end
    
    
//     always @(posedge (ft_clk)) begin
//         D_state_q <= D_state_d;
        
//     end
// endmodule