/*
    This file was generated automatically by Alchitry Labs 2.0.30-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/
// package LucidGlobals;
    
//     typedef struct packed {
//         logic [27:0] addr;
//         logic [2:0] cmd;
//         logic enable;
//         logic [127:0] wr_data;
//         logic wr_enable;
//         logic [15:0] wr_mask;
//     } G_Memory_in;
//     typedef struct packed {
//         logic [127:0] rd_data;
//         logic rd_valid;
//         logic rdy;
//         logic wr_rdy;
//     } G_Memory_out;
    
// endpackage