/*
    This file was generated automatically by Alchitry Labs 2.0.30-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module reset_conditioner #(
        parameter STAGES = 3'h4
    ) (
        input wire clk,
        input wire in,
        output reg out
    );
    logic [(STAGES)-1:0] D_stage_d, D_stage_q = {STAGES{1'h1}};
    always @* begin
        D_stage_d = D_stage_q;
        
        D_stage_d = {D_stage_q[STAGES - 2'h2:1'h0], 1'h0};
        out = D_stage_q[STAGES - 1'h1];
    end
    
    
    always @(posedge (clk) or posedge (in)) begin
        if ((in) == 1'b1) begin
            D_stage_q <= {STAGES{1'h1}};
        end else begin
            D_stage_q <= D_stage_d;
        end
    end
endmodule